version: '2.20'

services:
  app:
    image: gregatemi/jaythree:latest
    volumes:
      - .:/code
    environment:
      - .env
    ports:
      - "8005:8005"
    command: runserver 0.0.0.0:8005
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

    volumes:
      - /var/lib/docker/volumes/db/_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: gregatemi/nginx_server:v1
    volumes:
      - /var/lib/docker/volumes/vol2/_data
    ports:
      - "85:85"
    depends_on:
      - app

volumes:
  static: