version: '3'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    image: gregatemi/nginx_server:v4
    build:
      context: .
    volumes:
      - ./default.conf:/etc/nginx/default.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    image: gregatemi/jaythree:v4
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecret
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
