version: '3'

services:
  db:
    image: postgres:15
    environment:
      # - .env_db
      - POSTGRES_HOST_AUTH_METHOD=trust
      # - POSTGRES_DB = mydb
      # - POSTGRES_USER = myuser
      # - POSTGRES_PASSWORD = password
      
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
       
  django_gunicorn:
    image: gregatemi/app:latest
    volumes:
      - /var/lib/docker/volumes/vol1/_data
    environment:
      - .env
    build:
      context: .
    ports:
      - "8005:8005"

  nginx:
    image: gregatemi/nginx_server:latest
    build:
      context: .
    volumes:
      - /var/lib/docker/volumes/vol2/_data
    ports:
      - "85:85"
    depends_on:
      - django_gunicorn
      - db

volumes:
  static:
