version: '3'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      # - .env_db
      # - POSTGRES_DB = mydb
      # - POSTGRES_USER = myuser
      # - POSTGRES_PASSWORD = password
      
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
       
  django_gunicorn:
    image: gregatemi/jaythree:latest
    environment:
      - .env
    build:
      context: .
    ports:
      - "8005:8005"
      
  nginx:
    image: nginx
    build:
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "85:85"
    depends_on:
      - django_gunicorn
      - db

volumes:
  static:
