version: '2.20'

services:
  db:
    image: postgres:15
    environment:
      # - .env
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    volumes:
      - /var/lib/docker/volumes/db/_data

  app:
    image: gregatemi/jaythree:latest
    # volumes:
    #   - /var/lib/docker/volumes/vol1/_data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - .env
    # build:
    #   context: .
    ports:
      - "8005:8005"
    command: runserver 0.0.0.0:8005

  nginx:
    # build: ./nginx
    image: gregatemi/nginx_server:v1
    volumes:
      - /var/lib/docker/volumes/vol2/_data
    ports:
      - "85:85"
    depends_on:
      - app
      - db

volumes:
  static: