version: '3'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  # nginx:
  #   build:
  #     context: .
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/
  #     - ./html:/usr/share/nginx/html
  #     # - staticfiles:/home/Desktop/Projects/jaythree/app/staticfiles
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app

  app:
    image: gregatemi/jaythree:latest
    # build: .
    ports:
      - "8005:8005"
    # command: python manage.py runserver
    # command: gunicorn --bind 0.0.0.0:8000 jaythree.wsgi:application
    volumes: 
      - ./app:/app
    environment:
      - SECRET_KEY=devsecret
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
