- name: Deployment on an ON PREMISE VM instance
  hosts: all
  become: true
  become_method: sudo
  vars:
    ansible_become_pass: "Gatemi"
  tasks:
    - name: Install required system packages
      dnf:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - sshpass
        - curl
        - python3-pip
        - python3.11-venv
        - virtualenv
        - python3-setuptools
        - docker
        - docker-compose
      become: true

    - name: Recursively change ownership of a directory
      file:
        path: /home/sandbox/jaythree
        state: directory
        recurse: yes
        owner: sandbox
      become: true

    - name: Clone Docker Compose repository from Local
      copy:
        src: ./docker-compose.yml
        dest: jaythree/docker-compose.yml
    
    - name: Orchestrate containers
      command: docker-compose -f /home/sandbox/jaythree/docker-compose.yml build -d

    - name: Spin up the containers
      command: docker-compose -f /home/sandbox/jaythree/docker-compose.yml up -d
