- name: Deployment on a GCP VM instance
  hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - curl
        - python3-pip
        - python3.11-venv
        - virtualenv
        - python3-setuptools
        - docker
        - docker-compose
      become: true

    - name: Recursively change ownership of a directory
      file:
        path: /home/magrega/jaythree
        state: directory
        recurse: yes
        owner: magrega
      become: true

    - name: Clone Docker Compose repository from Local
      copy:
        src: ./docker-compose.yml
        dest: jaythree/docker-compose.yml
    
    - name: Orchestrate containers
      command: docker-compose -f /home/magrega/jaythree/docker-compose.yml build -d

    - name: Spin up the containers
      command: docker-compose -f /home/magrega/jaythree/docker-compose.yml up -d
