- name: Deployment on a GCP VM instance
  hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest
      loop: ['curl','python3-pip','python3.11-venv', 'virtualenv', 'python3-setuptools']
      become: true

    - name: Recursively change ownership of a directory
      file:
        path: /home/magrega/jaythree
        state: directory
        recurse: yes
        owner: magrega
      become: true

    - name: Clone Docker Compose repository from Local
      copy:
        src: ./docker-compose.yml
        dest: jaythree/docker-compose.yml
    
    - name: Pull App Docker image
      command: docker image pull gregatemi/jaythree:v6

    - name: Pull Nginx Server Docker image
      command: docker image pull gregatemi/nginx_server:v7

    - name: Pull Postgres Docker image
      command: docker image pull postgres:15
    
    # - name: Pull Docker images
    #   docker-image:
    #     name: "{{ image.name }}"
    #     tag: "{{ image.tag }}"
    #     state: present
    #   with_items:
    #     - { name: "gregatemi/nginx_server", tag: "v3" }
    #     - { name: "gregatemi/jaythree", tag: "v3" }
    #     - { name: "postgres", tag: "15" }

    # - name: Clone Dockerfile repository from Local
    #   copy:
    #     src: ./Dockerfile
    #     dest: jaythree/Dockerfile
    
    # - name: Orchestrate containers
    #   command: docker-compose -f /home/magrega/jaythree/docker-compose.yml build -d
    #   # command: docker-compose build

    - name: Spin up the containers
      command: docker-compose -f /home/magrega/jaythree/docker-compose.yml up -d
      # command: docker-compose up
