# Generated by Django 4.2.7 on 2024-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_product_product_id_alter_sale_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitems',
            name='id',
        ),
        migrations.AddField(
            model_name='saleitems',
            name='saleItem_id',
            field=models.SmallAutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
